name: LifeInJapan
favicon: null
layout_spectrum: 0.894431293476373
typography_spectrum: 0.025642543099820614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6734698852524161
  lightness: 0.1767103502061218
  saturation: 0.9679966864641756
  rhythmicContrast: 0.07681545871309936
purpose: []
